services:
  config-server:
    image: niptuss/config-server:latest
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  eureka-server:
    image: niptuss/eureka-server:latest
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    env_file:
      - ./env/eureka.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  gateway-server:
    image: niptuss/gateway-server:latest
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    env_file:
      - ./env/gateway.env

  customer-db:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  executive-db:
    image: postgres
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=executive-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d executive-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  loan-db:
    image: postgres
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=loan-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d loan-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  request-db:
    image: postgres
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=request-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d request-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  simulation-db:
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=simulation-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simulation-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ms-customer:
    image: niptuss/ms-customer:latest
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      customer-db:
        condition: service_healthy
    env_file:
      - ./env/customer.env

  ms-executive:
    image: niptuss/ms-executive:latest
    ports:
      - "8082:8082"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      executive-db:
        condition: service_healthy
    env_file:
      - ./env/executive.env

  ms-loan:
    image: niptuss/ms-loan:latest
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      loan-db:
        condition: service_healthy
    env_file:
      - ./env/loan.env

  ms-request:
    image: niptuss/ms-request:latest
    ports:
      - "8084:8084"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      request-db:
        condition: service_healthy
    env_file:
      - ./env/request.env

  ms-simulation:
    image: niptuss/ms-simulation:latest
    ports:
      - "8085:8085"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      simulation-db:
        condition: service_healthy
    env_file:
      - ./env/simulation.env

  frontend-ms:
    image: niptuss/frontend-ms:latest
    ports:
      - "80:80"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    env_file:
      - ./env/frontend.env
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=alerting
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
