services:
  config-server:
    image: niptuss/config-server:latest
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10

  eureka-server:
    image: niptuss/eureka-server:latest
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    env_file:
      - ./env/eureka.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10


  gateway-server:
    image: niptuss/gateway-server:latest
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    env_file:
      - ./env/gateway.env

  customer-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=customer-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customer-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ms-customer:
    image: niptuss/ms-customer:latest
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      customer-db:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_LOCATION=http://config-server:8888
      - HOSTNAME=ms-customer
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka
      - SERVER_PORT=8081
      - DB_HOST=customer-db
      - DB_PORT=5432
      - DB_DBNAME=customer-db
      - DB_USER=postgres
      - DB_PASSWORD=admin
