server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL_DEPLOYMENT}
  instance:
    hostname: ${GATEWAY_SERVER_SERVICE}
    non-secure-port: 8080
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/api/users/**
        - id: ms-simulation
          uri: lb://ms-simulation
          predicates:
            - Path=/api/simulation/**
        - id: ms-executive
          uri: lb://ms-executive
          predicates:
            - Path=/api/executive/**
        - id: ms-loan
          uri: lb://ms-loan
          predicates:
            - Path=/api/loan/**
        - id: ms-request
          uri: lb://ms-request
          predicates:
            - Path=/api/request/**