server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://executive-db-service:5433/executive-db
    username: postgres
    password: admin
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
