server:
  port: 8094
spring:
  datasource:
    url: jdbc:postgresql://loan-db-service:5436/loan-db
    username: postgres
    password: admin
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/