server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://request-db-service:5435/request-db
    username: postgres
    password: admin
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/