server:
  port: 8095
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/request-db
    username: postgres
    password: admin
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/