server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://request-db-service:5435/request-db
    username: postgres
    password: admin
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    preferIpAddress: false
    hostname: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/