apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: niptuss/frontend-ms
          ports:
            - containerPort: 80
          env:
            - name: VITE_BACKEND_SERVER
              value: "gateway-server-service"
            - name: VITE_BACKEND_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
