apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server-deployment
  labels:
    app: gateway-server-deployment
spec:
  selector:
    matchLabels:
      app: gateway-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server-deployment
    spec:
      containers:
        - name: gateway-server
          image: niptuss/gateway-server
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVER_URL_DEPLOYMENT
              value: "http://eureka-server-service:8761/eureka"
            - name: GATEWAY_SERVER_SERVICE
              value: "gateway-server-service"
            - name: CONFIG_SERVER_LOCATION
              value: "http://config-server-service:8888"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server-service
  labels:
    app: gateway-server-service
spec:
  selector:
    app: gateway-server-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer