apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-customer-deployment
  labels:
    app: ms-customer-deployment
spec:
  selector:
    matchLabels:
      app: ms-customer-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-customer-deployment
    spec:
      containers:
        - name: ms-customer
          image: niptuss/ms-customer
          env:
            - name: SERVER_PORT
              value: "0"
            - name: INSTANCE_HOSTNAME
              value: ms-customer
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CUSTOMER
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CUSTOMER
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CUSTOMER
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CUSTOMER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CUSTOMER