apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-executive-deployment
  labels:
    app: ms-executive-deployment
spec:
  selector:
    matchLabels:
      app: ms-executive-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-executive-deployment
    spec:
      containers:
        - name: ms-executive
          image: niptuss/ms-executive
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_EXECUTIVE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_EXECUTIVE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_EXECUTIVE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_EXECUTIVE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_EXECUTIVE