apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-loan-deployment
  labels:
    app: ms-loan-deployment
spec:
  selector:
    matchLabels:
      app: ms-loan-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-loan-deployment
    spec:
      containers:
        - name: ms-loan
          image: niptuss/ms-loan
          ports:
            - containerPort: 8094
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_LOAN
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_LOAN
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_LOAN
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_LOAN
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_LOAN