apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-request-deployment
  labels:
    app: ms-request-deployment
spec:
  selector:
    matchLabels:
      app: ms-request-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-request-deployment
    spec:
      containers:
        - name: ms-request
          image: niptuss/ms-request
          ports:
            - containerPort: 8095
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_REQUEST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_REQUEST
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_REQUEST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_REQUEST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_REQUEST