apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-simulation-deployment
  labels:
    app: ms-simulation-deployment
spec:
  selector:
    matchLabels:
      app: ms-simulation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-simulation-deployment
    spec:
      containers:
        - name: ms-simulation
          image: niptuss/ms-simulation
          ports:
            - containerPort: 0
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_SIMULATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_SIMULATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_SIMULATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_SIMULATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_SIMULATION
---
apiVersion: v1
kind: Service
metadata:
  name: ms-simulation-service
  labels:
    app: ms-simulation-service
spec:
  selector:
    app: ms-simulation-deployment
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
  type: ClusterIP